[package]
name = "dents"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
deno_core = "0.171.0"
tokio = { version = "1.25.0", features = ["full"] }
rusqlite = { version = "0.28.0", features = ["bundled"] }
