function isOwner({ user }, post) {
  return user.id === post.user_id;
}

export const rules = [
  {
    // this rule is generated by default
    role: "service_role",
    create: true,
    get: true,
    update: true,
    delete: true,
  },
  {
    role: "user_role",
    table: "posts",
    create: function ({ user }) {
      return user != null;
    },
    get: function (_, post) {
      return post.status === "published";
    },
    update: isOwner,
    delete: isOwner,
  },
];
